version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    commit-message:
      prefix: "meta-*: "
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      layers:
        patterns:
          - "meta-*"
          - "poky"
